- name: Actualizar Servidores
  hosts: all
  tasks:
    - name: Descargar e instalar actualizaciones de Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: true
        state: search
      register: pending_updates
      until: pending_updates.updates_found == false
      retries: 60
      delay: 300
