- name: Actualizar Servidores
  hosts: srv-cloud.mdar.aerolineas.com.ar
  tasks:
    - name: Descargar e instalar actualizaciones de Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: true
        log_path: C:\ansible_wu.txt
