- name: Crear VMware Snapshot
  hosts: vd-cloud
  gather_facts: false
  tasks:
    - name: Crear snapshot
      vmware_guest_snapshot:
        validate_certs: no
        name: vd-cloud
        state: present
        description: "Snapshot created by Ansible Tower"
