---
- name: Create a snapshot
  hosts: all
  tasks:
    - name: Crear un snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: arsrv197.mdar.aerolineas.com.ar
        username: ar031692adm@mdar.aerolineas.com.ar
        password: 2023*Arsaprod
        datacenter: CIP Ezeiza
        folder: "/"
        datastore: vsanDatastore
        cluster: Cluster vSAN
        state: present
        snapshot_name: Snapshot created by Ansible Tower
        description: snap1_description
        tags:
        - snapshot
      register: snapshot_result
 
    - name: Verificar si la creación de snapshot fue exitosa
      fail:
        msg: "Error al crear el snapshot. Detalles: {{ snapshot_result }}"
      when: snapshot_result.failed
      tags:
        - snapshot

- name: Actualizar Servidores
  hosts: all
  tasks:
    - name: Descargar e instalar actualizaciones de Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: true
      tags:
        - updates
    - name: Verificar si quedan actualizaciones pendientes después del reinicio
      win_updates:
        state: searched
      register: pending_updates
    - name: Mostrar listado de actualizaciones pendientes
      debug:
        var: pending_updates.updates
      tags:
        - updates
