- name: Crear snapshot y actualizar Windows Servers
  hosts: 10.100.28.11
  gather_facts: no
  tasks:
    - name: Crear snapshot con VMware
      community.vmware.vmware_vm_vm_drs_rule:
        hostname: arsrv197.mdar.aerolineas.com.ar
        username: ar031692adm
        password: 2023*Arsaprod
        validate_certs: no
        vm_username: ar031692adm
        vm_password: 2023*Arrsaprod
        name: "Snapshot previo a actualización"
        state: present
