- name: Actualizar Servidores
  hosts: all
  tasks:
    - name: Descargar e instalar actualizaciones de Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: true
    - name: Notificar si no hay actualizaciones pendientes
      debug:
        msg: "El sistema está actualizado, no hay actualizaciones pendientes."
      when: pending_updates.updates_found == false
