---
- name: Crear snapshot y actualizar Windows Servers
  hosts: all
  tasks:
    - name: Crear snapshot con VMware
      vmware_guest_snapshot:
        validate_certs: no
        vm_username: ar031692adm@mdar.aerolineas.com.ar
        vm_password: 2023*Arsaprod
        name: "Snapshot previo a actualización"
        state: present

- name: Actualizar Servidores
  hosts: all
  tasks:
    - name: Descargar e instalar actualizaciones de Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: true
    - name: Verificar si quedan actualizaciones pendientes después del reinicio
      win_updates:
        state: searched
      register: pending_updates
    - name: Mostrar listado de actualizaciones pendientes
      debug:
        var: pending_updates.updates
