---
- name: Create a snapshot
  community.vmware.vmware_guest_snapshot:
    hostname: "{{ arsrv197.mdar.aerolineas.com.ar }}"
    username: "{{ ar031692adm@mdar.aerolineas.com.ar }}"
    password: "{{ 2023*Arsaprod }}"
    datacenter: "{{ CIP Ezeiza }}"
    folder: "/{{ / }}/vm/"
    name: "{{ ar031692adm }}"
    state: present
    snapshot_name: snap1
    description: snap1_description
  delegate_to: localhost

- name: Actualizar Servidores
  hosts: all
  tasks:
    - name: Descargar e instalar actualizaciones de Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: true
    - name: Verificar si quedan actualizaciones pendientes después del reinicio
      win_updates:
        state: searched
      register: pending_updates
    - name: Mostrar listado de actualizaciones pendientes
      debug:
        var: pending_updates.updates
