- name: Crear VMware Snapshot
  hosts: vd-cloud
  gather_facts: false
  tasks:
    - name: Crear snapshot
      vmware_guest_snapshot:
        validate_certs: no
        name: "{{ inventory_hostname }}"
        state: present
        description: "Snapshot created by Ansible Tower"
        
- name: Actualizar Servidores
  hosts: all
  tasks:
    - name: Descargar e instalar actualizaciones de Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: true
    - name: Verificar si quedan actualizaciones pendientes después del reinicio
      win_updates:
        state: searched
      register: pending_updates
    - name: Mostrar listado de actualizaciones pendientes
      debug:
        var: pending_updates.updates
